openapi: 3.0.0

info:
  title: Test_API_call
  description: Calls test API endpoint from dummy json.
  version: "v2"

servers:
  - url: https://dummyjson.com/

paths:
  /test:
    get:
      operationId: Test_API_call
      summary: Check IP address info using IP-API
      # parameters:
      #   - in: path
      #     name: ip
      #     schema:
      #       type: string
      #     required: true
      #     description: The IP address to check
      responses:
        '200':
          description: IP information retrieved successfully
        '400':
          description: Invalid IP address or parameters
        '429':
          description: Rate limit exceeded
