openapi: 3.0.3
info:
  title: Compliance and Risk reporting agent
  description: This agent evaluates device and security configuration data collected from Beak RMM against defined compliance frameworks.
  version: 1.0.0
servers:
  - url: https://ai-qa.beakops.com/api/bitc
paths:
  /runs/copilot/stream:
    post:
      summary: Compliance and Risk reporting agent (response)
      operationId: ComplianceRiskReportingAgent
      tags:
        - ComplianceRiskReportingAgent
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  description: The message sent to the agent.
                  example: Hi
      responses:
        '200':
          description: Streamed response from the agent.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The response message from the copilot.
        '400':
          description: Bad request (e.g. invalid assistant_id).
        '401':
          description: Unauthorized (invalid API key).
        '500':
          description: Internal server error.
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: API-Key
