openapi: 3.0.1
info:
  title: Microsoft Graph Security - Email Remediation API
  version: 1.0.0
  description: >
    OpenAPI definition for calling the Microsoft Graph Security API
    to remediate suspicious emails by moving them to Junk.

servers:
  - url: https://graph.microsoft.com/beta

paths:
  /security/collaboration/analyzedEmails/remediate:
    post:
      summary: Remediate (move suspicious email to Junk)
      description: >
        Creates a remediation action that moves a suspicious email to the Junk folder.
        Requires application permissions (e.g., `Mail.ReadWrite`, `SecurityActions.ReadWrite.All`).
      operationId: RemediateAnalyzedEmail
      security:
        - azureAdAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - displayName
                - description
                - severity
                - action
                - analyzedEmails
              properties:
                displayName:
                  type: string
                  description: A friendly display name for the remediation.
                  example: Move suspicious email to Junk
                description:
                  type: string
                  description: A description of the remediation action.
                  example: Remediation automated by script
                severity:
                  type: string
                  enum: [low, medium, high]
                  description: Severity level for the remediation.
                  example: medium
                action:
                  type: string
                  enum: [moveToJunk, softDelete, hardDelete]
                  description: Action to take on the suspicious email.
                  example: moveToJunk
                remediateSendersCopy:
                  type: boolean
                  description: Whether to remediate the sender’s copy as well.
                  example: false
                analyzedEmails:
                  type: array
                  description: List of analyzed emails to remediate.
                  items:
                    type: object
                    required:
                      - networkMessageId
                      - recipientEmailAddress
                    properties:
                      networkMessageId:
                        type: string
                        description: The unique ID of the network message.
                        example: 0280f2cc-b1e6-442b-485c-08dde4cf6818
                      recipientEmailAddress:
                        type: string
                        description: The email address of the recipient.
                        example: manivannan@limslabs.onmicrosoft.com
      responses:
        "200":
          description: Remediation request submitted successfully.
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "Email moved to Junk folder."
        "401":
          description: Unauthorized – invalid or missing token.
        "403":
          description: Forbidden – insufficient Graph API permissions.
        "500":
          description: Internal server error.

components:
  securitySchemes:
    azureAdAuth:
      type: oauth2
      description: Use OAuth2 client credentials flow with Azure AD to authenticate.
      flows:
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token
          scopes:
            https://graph.microsoft.com/.default: Access Microsoft Graph API
