openapi: 3.0.1
info:
  title: MoveToJunk API
  description: API to move suspicious emails to the Junk folder using Microsoft Graph Security.
  version: 1.0.0
servers:
  - url: https://graph.microsoft.com/beta
paths:
  /security/collaboration/analyzedEmails/remediate:
    post:
      summary: Move suspicious email to Junk
      description: Moves an analyzed email to the Junk folder.
      operationId: moveToJunk
      security:
        - oauth2: [https://graph.microsoft.com/.default]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                displayName:
                  type: string
                  example: "Move suspicious email to Junk"
                description:
                  type: string
                  example: "Remediation automated by Security Copilot plugin"
                severity:
                  type: string
                  enum: [low, medium, high]
                  example: "medium"
                action:
                  type: string
                  enum: [moveToJunk]
                  example: "moveToJunk"
                remediateSendersCopy:
                  type: boolean
                  example: false
                analyzedEmails:
                  type: array
                  items:
                    type: object
                    properties:
                      networkMessageId:
                        type: string
                        example: "0280f2cc-b1e6-442b-485c-08dde4cf6818"
                      recipientEmailAddress:
                        type: string
                        example: "manivannan@limslabs.onmicrosoft.com"
      responses:
        '200':
          description: Email moved to Junk successfully.
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad Request – Invalid input.
        '401':
          description: Unauthorized – Access token missing or invalid.
        '403':
          description: Forbidden – Insufficient permissions.
        '500':
          description: Internal Server Error.
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token
          scopes:
            https://graph.microsoft.com/.default: Access Microsoft Graph API
