openapi: 3.0.0
info:
  title: VirusTotal URL Analysis API
  version: 1.0.0
  description: |
    This API retrieves analysis reports for a given URL using VirusTotal's API v3.
servers:
  - url: https://www.virustotal.com/api
paths:
  /v3/urls/{url}:
    get:
      summary: Get VirusTotal URL threat intelligence for an URL
      operationId: BeakUrlAnalysis
      parameters:
        - name: url
          in: path
          description: The url given provided by the user and passed to the API endpoint.
          required: true
          schema:
            type: string
            example: 'https://www.kvms.org.in/'
      responses:
        "200":
          description: Successful retrieval of URL analysis report
      security:
        - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-apikey
